# Generated by Django 3.2.15 on 2022-10-03 17:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('biog', models.TextField(blank=True, max_length=500, null=True)),
                ('genre1', models.CharField(blank=True, choices=[('POP', 'Pop'), ('ROC', 'Rock'), ('HIP', 'Hip Hop'), ('FUS', 'Fusion'), ('CLA', 'Classical')], max_length=3, null=True)),
                ('instru_skill1', models.CharField(blank=True, max_length=30, null=True)),
                ('friends', models.ManyToManyField(blank=True, default=None, null=True, related_name='_songmates_main_profile_friends_+', to='songmates_main.Profile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
