# Generated by Django 3.2.15 on 2022-10-03 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songmates_main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='friends',
            field=models.ManyToManyField(blank=True, null=True, related_name='_songmates_main_profile_friends_+', to='songmates_main.Profile'),
        ),
    ]
