# Generated by Django 3.2.15 on 2022-10-07 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songmates_main', '0003_auto_20221007_0834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='_songmates_main_profile_friends_+', to='songmates_main.Profile'),
        ),
    ]
