# Generated by Django 3.2.15 on 2022-10-13 11:46

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songmates_main', '0006_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=cloudinary.models.CloudinaryField(default='blank-profile-pic.png', max_length=255, verbose_name='image'),
        ),
    ]
