# Generated by Django 3.2.15 on 2022-10-21 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songmates_main', '0009_collabrequest'),
    ]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name='profile',
            order_with_respect_to='user',
        ),
    ]
