# Generated by Django 3.2.15 on 2022-10-21 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songmates_main', '0010_alter_profile_order_with_respect_to'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['user__username']},
        ),
        migrations.AlterOrderWithRespectTo(
            name='profile',
            order_with_respect_to=None,
        ),
    ]
