# Generated by Django 3.2.15 on 2022-10-21 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songmates_main', '0011_auto_20221021_1049'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={},
        ),
    ]
