# Generated by Django 3.2.15 on 2022-10-21 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songmates_main', '0012_alter_profile_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='slug',
        ),
    ]
