# Generated by Django 3.2.15 on 2022-10-21 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songmates_main', '0013_remove_profile_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='biog',
            field=models.TextField(blank=True, default="This user hasn't updated their profile yet.", max_length=500, null=True),
        ),
    ]
