# Generated by Django 3.2.15 on 2022-10-21 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songmates_main', '0015_alter_profile_biog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='biog',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
