# Generated by Django 3.2.15 on 2022-10-21 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songmates_main', '0016_alter_profile_biog'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_complete',
            field=models.BooleanField(default=False),
        ),
    ]
